# Generated by Django 4.2.30 on 2026-08-19 19:21

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('code_ana', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código ANA')),
                ('code_inmet', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código INMET')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Estação')),
                ('station_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('sub_basin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Bacia')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('responsible', models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsável')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Geometria (Lat/Lon)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data Inicial (StartDate)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Final (EndDate)')),
                ('nyd', models.FloatField(blank=True, null=True, verbose_name='Anos com Dados (NYD)')),
                ('md', models.FloatField(blank=True, null=True, verbose_name='Dados Faltantes/Missing (MD)')),
                ('n_ywomd', models.FloatField(blank=True, null=True, verbose_name='Anos sem Falhas (N_YWOMD)')),
                ('ywmd', models.FloatField(blank=True, null=True, verbose_name='Anos com Falhas (YWMD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado no Sistema em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro.state')),
            ],
            options={
                'verbose_name': 'Estação Meteorológica',
                'verbose_name_plural': 'Estações Meteorológicas',
                'db_table': 'hydro_station',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Tarefa (Celery)')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Tarefa / Processo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('SUCCESS', 'Concluído'), ('FAILED', 'Erro')], default='PENDING', max_length=20, verbose_name='Status')),
                ('result_message', models.TextField(blank=True, null=True, verbose_name='Resultado / Detalhes')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Log de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
            ],
            options={
                'verbose_name': 'Relatório de Tarefa',
                'verbose_name_plural': 'Relatórios de Tarefas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_id'], name='hydro_taskr_task_id_33f8ef_idx'), models.Index(fields=['status'], name='hydro_taskr_status_062afd_idx'), models.Index(fields=['created_at'], name='hydro_taskr_created_e378db_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrecipitationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Leitura')),
                ('value_ana', models.FloatField(blank=True, null=True, verbose_name='Precipitação ANA (mm)')),
                ('is_gap_ana', models.BooleanField(default=False, verbose_name='Falha ANA?')),
                ('value_inmet', models.FloatField(blank=True, null=True, verbose_name='Precipitação INMET (mm)')),
                ('is_gap_inmet', models.BooleanField(default=True, verbose_name='Falha INMET?')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitation_records', to='hydro.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Registro Pluviométrico',
                'verbose_name_plural': 'Registros Pluviométricos',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['station', 'date'], name='hydro_preci_station_309403_idx'), models.Index(fields=['is_gap_ana'], name='hydro_preci_is_gap__f08822_idx'), models.Index(fields=['is_gap_inmet'], name='hydro_preci_is_gap__75d274_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='precipitationrecord',
            constraint=models.UniqueConstraint(fields=('station', 'date'), name='unique_station_date_precipitation'),
        ),
    ]
