# Generated by Django 4.2.30 on 2026-08-11 00:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código ANA')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Estação')),
                ('station_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('sub_basin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Bacia')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('responsible', models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsável')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Geometria (Lat/Lon)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data Inicial (StartDate)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Final (EndDate)')),
                ('nyd', models.FloatField(blank=True, null=True, verbose_name='Anos com Dados (NYD)')),
                ('md', models.FloatField(blank=True, null=True, verbose_name='Dados Faltantes/Missing (MD)')),
                ('n_ywomd', models.FloatField(blank=True, null=True, verbose_name='Anos sem Falhas (N_YWOMD)')),
                ('ywmd', models.FloatField(blank=True, null=True, verbose_name='Anos com Falhas (YWMD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado no Sistema em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Estação Meteorológica',
                'verbose_name_plural': 'Estações Meteorológicas',
                'db_table': 'hydro_station',
                'ordering': ['state', 'name'],
            },
        ),
    ]
