# Generated by Django 4.2.30 on 2026-08-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
