# Generated by Django 4.2.30 on 2026-08-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0002_alter_station_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
    ]
