# Generated by Django 4.2.30 on 2026-08-13 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0003_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecipitationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Leitura')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Precipitação (mm)')),
                ('is_gap', models.BooleanField(default=False, verbose_name='Possui Falha?')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitation_records', to='hydro.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Registro Pluviométrico',
                'verbose_name_plural': 'Registros Pluviométricos',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['station', 'date'], name='hydro_preci_station_309403_idx'), models.Index(fields=['is_gap'], name='hydro_preci_is_gap_b33944_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='precipitationrecord',
            constraint=models.UniqueConstraint(fields=('station', 'date'), name='unique_station_date_precipitation'),
        ),
    ]
