# Generated by Django 4.2.30 on 2026-08-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydro', '0004_precipitationrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Tarefa (Celery)')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Tarefa / Processo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('SUCCESS', 'Concluído'), ('FAILED', 'Erro')], default='PENDING', max_length=20, verbose_name='Status')),
                ('result_message', models.TextField(blank=True, null=True, verbose_name='Resultado / Detalhes')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Log de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
            ],
            options={
                'verbose_name': 'Relatório de Tarefa',
                'verbose_name_plural': 'Relatórios de Tarefas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_id'], name='hydro_taskr_task_id_33f8ef_idx'), models.Index(fields=['status'], name='hydro_taskr_status_062afd_idx'), models.Index(fields=['created_at'], name='hydro_taskr_created_e378db_idx')],
            },
        ),
    ]
