# Generated by Django 4.2.30 on 2026-08-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0005_taskreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Estado'),
        ),
    ]
