# Generated by Django 4.2.30 on 2026-08-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0006_alter_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='state_where',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro.state'),
        ),
    ]
