# Generated by Django 4.2.30 on 2026-08-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0007_station_state_where'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['state_where', 'name'], 'verbose_name': 'Estação Meteorológica', 'verbose_name_plural': 'Estações Meteorológicas'},
        ),
        migrations.RemoveField(
            model_name='station',
            name='state',
        ),
    ]
