# Generated by Django 4.2.30 on 2026-08-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0008_alter_station_options_remove_station_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['state', 'name'], 'verbose_name': 'Estação Meteorológica', 'verbose_name_plural': 'Estações Meteorológicas'},
        ),
        migrations.RenameField(
            model_name='station',
            old_name='state_where',
            new_name='state',
        ),
    ]
